name: ci

on:
  push:
  pull_request:

jobs:

  builds:

    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.23 ]
        dotnet-version: [ 9.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Install .DotNet
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
        with:
          dotnet-version: |
            ${{ matrix.dotnet-version }}

      - name: Build
        run: make build image-build

  tests:
    strategy:
      matrix:
        name: [unit]
        go-version: [ 1.23 ]
    runs-on: ubuntu-latest
    name: test (${{ matrix.name }})
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Run ${{ matrix.name }} tests
        run: make test

